// Generates src/build-info.ts before tsc runs.
//
// TypeScript has no build-time "define", so the release sign is passed as an
// environment variable to this script, which writes it into a source file that
// the compiler then bundles into the build.
//
//   MINIAGENT_RELEASE=1 pnpm build   # release build
//   pnpm build                       # development build
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

const raw = process.env.MINIAGENT_RELEASE?.trim().toLowerCase()
const release = raw !== undefined && raw !== '' && raw !== '0' && raw !== 'false'
const version = process.env.MINIAGENT_VERSION ?? pkg.version ?? '0.0.0'

const contents = `// Generated by scripts/build-info.mjs. Do not edit; run the build instead.

/** Whether MINIAGENT_RELEASE was set when this build was produced. */
export const RELEASE = ${release}

/** Version stamped at build time, from package.json. */
export const VERSION = ${JSON.stringify(version).replaceAll('"', "'")}
`

const target = join(root, 'src', 'build-info.ts')

let existing = ''
try {
  existing = readFileSync(target, 'utf8')
} catch {
  // first generation
}

if (existing === contents) {
  console.log(`[build-info] unchanged (release=${release}, version=${version})`)
} else {
  writeFileSync(target, contents)
  console.log(`[build-info] wrote src/build-info.ts (release=${release}, version=${version})`)
}
